default_config:

homeassistant:
  packages: !include_dir_named packages

lovelace:
  mode: yaml
  resources:
    - url: /local/restriction-card.js
      type: module
    - url: /local/button-card.js
      type: module
    - url: /local/layout-card.js
      type: module

frontend:
  extra_module_url:
    - /local/card-mod.js
